engine/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('user.login');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('registant', 'RegistantController');
    Route::get('registant/buktiKelengkapan/{index}/{id}', 'RegistantController@showKelengkapan')->name('registant.kelengkapan');
    Route::get('registant/buktiKompetensi/{index}/{id}', 'RegistantController@showKompetensi')->name('registant.kompetensi');
    Route::get('/registant/cluster/{id}', 'RegistantController@showCluster');
    Route::get('/registant/competency/{id}', 'RegistantController@showCompetency');
    Route::resource('assessor', 'AssessorController');
    Route::resource('scheme', 'SchemeController');
    Route::resource('competency', 'CompetencyController');
    Route::resource('participant', 'ParticipantController');
    Route::get('participant/apl/02/detail/{id_participant}/{id_cluster}', 'ParticipantController@detailApl02')->name('participant.apl02');
    Route::post('participant/apl/02/detail/{id_participant}/{id_asesor}', 'ParticipantController@detailApl02store')->name('participant.apl02.store');
    Route::post('participant/finish', 'ParticipantController@finish')->name('participant.finish');
    Route::resource('element', 'ElementController');
    Route::resource('question', 'QuestionController');
    Route::resource('school', 'SchoolController');
    Route::get('print/{id_participant}', 'PrintController@printAssignment')->name('print.assignment');
    Route::get('print/apl/02/{id_participant}/{id_cluster}/{id_asesor}', 'PrintController@printForm')->name('print.form');
});

Route::get('/login', 'AuthController@login')->name('user.login');
Route::get('/logout', 'AuthController@logout')->name('user.logout');
Route::get('/change/password', 'AuthController@editPassword')->name('user.change.password');
Route::put('/change/password', 'AuthController@updatePassword')->name('user.change.password.store');
Route::post('/loginPost', 'AuthController@loginPost')->name('user.login.post');
Route::get('/register', 'AuthController@register')->name('user.register');
Route::get('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02')->name('user.register02');
Route::post('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02store')->name('user.register02.store');
Route::get('/register/confirm', 'AuthController@registerConfirm')->name('user.register02.confirm');

engine/resources/views/admin/elementCompetency/create.blade.php
@extends('admin.app')

@section('title', 'Tambah Data')

@section('content')


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Tambah Data
                </div>
                <div class="card-body">

                    <!-- route('admin.scheme.store) -->
                    <form action="" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Email address</label>
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Example select</label>
                            <select class="form-control" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option>2</option>
                            </select>
                        </div>                       
                        <div class="form-group">
                            <label for="exampleFormControlFile1">Example file input</label>
                            <input type="file" class="form-control-file" id="exampleFormControlFile1">
                        </div>
                        
                        <label>Example Radio Button</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                            <label class="form-check-label" for="exampleRadios1">
                                Default radio
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1">
                            <label class="form-check-label" for="exampleRadios1">
                                Second Default radio
                            </label>
                        </div>

                        
                        <button type="submit" class="btn btn-primary mt-3">
                            Tambah
                        </button>

                        
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

engine/resources/views/admin/elementCompetency/index.blade.php
@extends('admin.app')

@section('title', 'Skema')

@section('content')

            <link rel="stylesheet" href="{{URL::asset('public_html/__assets/css/lib/datatable/dataTables.bootstrap.min.css')}}">

            <div class="animated fadeIn">
                <div class="row">

                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Elemen Kompetensi</strong>
                            </div>

                            <div class="card-body">
                                @if(Session::get('role') == 'admin')
                                <div class="col-md-12 mb-2">
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#TambahData">
                                        Tambah Data
                                    </button>
                                </div>
                                @endif
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Kode Unit</th>
                                            <th>Elemen Kompetensi</th>
                                            @if(Session::get('role') == 'admin')
                                            <th>Opsi</th>
                                            @endif
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($data['element'] as $element)
                                        <tr>
                                            <td>{{$element->competency->kode_unit}}</td>
                                            <td>{{$element->elemen_kompetensi}}</td>
                                            @if(Session::get('role') == 'admin')
                                            <td class="d-flex justify-content-center">
                                                <button type="button" onclick="getEdit(this)" data-id="{{$element->id}}" class="btn btn-primary btn-sm mr-2" data-toggle="modal" data-target="#EditData">
                                                    Edit
                                                </button>
                                                 <form action="{{route('admin.element.destroy', $element->id)}}" method="POST">
                                                    @csrf
                                                    @method('DELETE')

                                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah anda yakin akan menghapus data?')">
                                                        Hapus
                                                    </button>
                                                 </form>
                                            </td>
                                            @endif
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <!-- Tambah Data -->
            <!-- route('admin.scheme.store') -->
            <div class="modal fade" id="TambahData" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Tambah Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{route('admin.element.store')}}">
                        @csrf
                            <div class="form-group">
                                <label>Unit Kompetensi</label>
                                <select class="form-control" required name="id_kompetensi">
                                    <option value="">-- Select Unit Kompetensi --</option>
                                    @foreach($data['competence'] as $competecy)
                                    <option value="{{$competecy->id}}">{{$competecy->kode_unit}} - {{$competecy->judul_unit}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Elemen Kompetensi</label>
                                <input type="text" class="form-control" name="elemen_kompetensi" placeholder="Masukkan Elemen Kompetensi" required autocomplete='off'>
                            </div>
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                    </div>
                </div>
            </div>

            <!-- Edit Data -->
            <!-- route('admin.scheme.update', $id) -->
            <div class="modal fade" id="EditData" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="" id="form">
                        @csrf
                            <input type="hidden" id="id" value="">
                            <div class="form-group">
                                <label>Unit Kompetensi</label>
                                <select class="form-control" required name="id_kompetensi" id="id_kompetensi">
                                    <option value="">-- Select Unit Kompetensi --</option>
                                    @foreach($data['competence'] as $competecy)
                                    <option value="{{$competecy->id}}">{{$competecy->kode_unit}} - {{$competecy->judul_unit}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Elemen Kompetensi</label>
                                <input type="text" class="form-control" name="elemen_kompetensi" id="elemen_kompetensi" placeholder="Masukkan Elemen Kompetensi" required autocomplete='off'>
                            </div>
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                    </div>
                    </div>
                </div>
            </div>


<script src="{{URL::asset('public_html/__assets/js/lib/data-table/datatables.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/dataTables.bootstrap.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/dataTables.buttons.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.bootstrap.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/jszip.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/vfs_fonts.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.html5.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.print.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.colVis.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/init/datatables-init.js')}}"></script>
<script>
    @if(Session::has('success'))
        alert('Elemen Kompetensi berhasil di tambah!')
    @endif
    @if(Session::has('delete'))
        alert('Elemen Kompetensi berhasil di hapus!')
    @endif
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#bootstrap-data-table-export').DataTable();
    });

    function getEdit(e) {
        var id = $(e).data('id')
        var url = '{{route("admin.element.index")}}/' + id + '/edit'

        $.ajax({
            method : 'get',
            url : url,
            dataType : 'json',
            success : function(data) {
                // console.log(data)
                $.each(data, function(i, item) {
                    $('#id').val(item.id)
                    $('#id_kompetensi').val(item.id_kompetensi)
                    $('#elemen_kompetensi').val(item.elemen_kompetensi)
                })
            }
        })
    }

    $('#form').on('submit', function(e) {
        e.preventDefault()
        var formData = $(this).serialize()
        var id = $('#id').val()
        var url = "{{route('admin.element.index')}}/" + id

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $.ajax({
            method : 'PUT',
            url : url,
            data : formData,
            success : function(data) {
                alert(data.message)
                location.reload()
            }
        })
    })
</script>

@endsection