engine/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('user.login');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('registant', 'RegistantController');
    Route::get('registant/buktiKelengkapan/{index}/{id}', 'RegistantController@showKelengkapan')->name('registant.kelengkapan');
    Route::get('registant/buktiKompetensi/{index}/{id}', 'RegistantController@showKompetensi')->name('registant.kompetensi');
    Route::get('/registant/cluster/{id}', 'RegistantController@showCluster');
    Route::get('/registant/competency/{id}', 'RegistantController@showCompetency');
    Route::resource('assessor', 'AssessorController');
    Route::resource('scheme', 'SchemeController');
    Route::resource('competency', 'CompetencyController');
    Route::resource('participant', 'ParticipantController');
    Route::get('participant/apl/02/detail/{id_participant}/{id_cluster}', 'ParticipantController@detailApl02')->name('participant.apl02');
    Route::post('participant/apl/02/detail/{id_participant}/{id_asesor}', 'ParticipantController@detailApl02store')->name('participant.apl02.store');
    Route::post('participant/finish', 'ParticipantController@finish')->name('participant.finish');
    Route::resource('element', 'ElementController');
    Route::resource('question', 'QuestionController');
    Route::resource('school', 'SchoolController');
    Route::get('print/{id_participant}', 'PrintController@printAssignment')->name('print.assignment');
    Route::get('print/apl/02/{id_participant}/{id_cluster}/{id_asesor}', 'PrintController@printForm')->name('print.form');
});

Route::get('/login', 'AuthController@login')->name('user.login');
Route::get('/logout', 'AuthController@logout')->name('user.logout');
Route::get('/change/password', 'AuthController@editPassword')->name('user.change.password');
Route::put('/change/password', 'AuthController@updatePassword')->name('user.change.password.store');
Route::post('/loginPost', 'AuthController@loginPost')->name('user.login.post');
Route::get('/register', 'AuthController@register')->name('user.register');
Route::get('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02')->name('user.register02');
Route::post('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02store')->name('user.register02.store');
Route::get('/register/confirm', 'AuthController@registerConfirm')->name('user.register02.confirm');

engine/app/Http/Controllers/CompetencyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

// model
use App\Competence;
use App\Cluster;

class CompetencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // validasi session login
        if(!Session::get('user')) {
            return redirect()->route('user.login');
        } else {
            // mengambil data komptensi
            $data['competency'] = Competence::orderBy('id_klaster', 'ASC')
                                    ->with('cluster')
                                    ->get();
            // mengambil data klaster
            $data['cluster']    = Cluster::orderBy('no_cluster', 'ASC')->get();

            return view('admin.competency.index', compact('data'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // mengambil data yang diinputkan user
        $kode_unit      = $request->kode_unit;
        $judul_unit     = $request->judul_unit;
        $jenis_standar  = $request->jenis_standar;
        $id_klaster     = $request->id_klaster;

        // menambah data ke database
        Competence::insert([
            'kode_unit' => $kode_unit,
            'judul_unit' => $judul_unit,
            'jenis_standar' => $jenis_standar,
            'id_klaster' => $id_klaster
        ]);

        return redirect()->route('admin.competency.index')->with('success', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // mencari data kompetensi sesuai id kompetensi
        $data = Competence::find($id);
        $data->first();

        return response()->json([
            'data' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // mengambil data yang diinputkan user
        $kode_unit      = $request->kode_unit;
        $judul_unit     = $request->judul_unit;
        $jenis_standar  = $request->jenis_standar;
        $id_klaster     = $request->id_klaster;

        // update data kompetensi di database
        Competence::where('id', $id)->update([
            'kode_unit' => $kode_unit,
            'judul_unit' => $judul_unit,
            'jenis_standar' => $jenis_standar,
            'id_klaster' => $id_klaster
        ]);

        return response()->json([
            'message' => 'Data Kompetensi berhasil di ubah!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // mencari data kompetensi sesuai id kompetensi
        $competency = Competence::find($id);
        // menghapus data kompetensi
        $competency->delete();

        return redirect()->route('admin.competency.index')->with('delete', true);
    }
}

engine/resources/views/admin/competency/create.blade.php
@extends('admin.app')

@section('title', 'Tambah Data')

@section('content')


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Tambah Data
                </div>
                <div class="card-body">

                    <!-- route('admin.scheme.store) -->
                    <form action="" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Email address</label>
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Example select</label>
                            <select class="form-control" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option>2</option>
                            </select>
                        </div>                       
                        <div class="form-group">
                            <label for="exampleFormControlFile1">Example file input</label>
                            <input type="file" class="form-control-file" id="exampleFormControlFile1">
                        </div>
                        
                        <label>Example Radio Button</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
                            <label class="form-check-label" for="exampleRadios1">
                                Default radio
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1">
                            <label class="form-check-label" for="exampleRadios1">
                                Second Default radio
                            </label>
                        </div>

                        
                        <button type="submit" class="btn btn-primary mt-3">
                            Tambah
                        </button>

                        
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

engine/resources/views/admin/competency/index.blade.php
@extends('admin.app')

@section('title', 'Skema')

@section('content')

            <link rel="stylesheet" href="{{URL::asset('public_html/__assets/css/lib/datatable/dataTables.bootstrap.min.css')}}">

            <div class="animated fadeIn">
                <div class="row">

                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Kompetensi</strong>
                            </div>

                            <div class="card-body">
                                @if(Session::get('role') == 'admin')
                                <div class="col-md-12 mb-2">
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#TambahData">
                                        Tambah Data
                                    </button>
                                </div>
                                @endif
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Kode Unit</th>
                                            <th>Judul Unit</th>
                                            <th>Jenis Standar</th>
                                            <th>No Cluster</th>
                                            @if(Session::get('role') == 'admin')
                                            <th>Opsi</th>
                                            @endif
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data['competency'] as $competency)
                                        <tr>
                                            <td>{{$competency->kode_unit}}</td>
                                            <td>{{$competency->judul_unit}}</td>
                                            <td>{{$competency->jenis_standar}}</td>
                                            <td>{{$competency->cluster->no_cluster}}</td>
                                            @if(Session::get('role') == 'admin')
                                            <td class="d-flex justify-content-center">
                                                <button type="button" onclick="getEdit(this)" data-id="{{$competency->id}}" class="btn btn-primary btn-sm mr-2" data-toggle="modal" data-target="#EditData">
                                                    Edit
                                                </button>
                                                 <form action="{{route('admin.competency.destroy', $competency->id)}}" method="POST">
                                                    @csrf
                                                    @method('DELETE')

                                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah anda yakin akan menghapus data?')">
                                                        Hapus
                                                    </button>
                                                 </form>
                                            </td>
                                            @endif
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>



            <!-- Tambah Data -->
            <!-- route('admin.scheme.store') -->
            <div class="modal fade" id="TambahData" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Tambah Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{route('admin.competency.store')}}">
                        @csrf
                            <div class="form-group">
                                <label>Unit Code</label>
                                <input type="text" class="form-control" name="kode_unit" placeholder="Enter Unit Code" required autocomplete='off'>
                            </div>
                            <div class="form-group">
                                <label>Unit Title</label>
                                <input type="text" class="form-control" name="judul_unit" placeholder="Enter Unit Title" required autocomplete='off'>
                            </div>
                            <div class="form-group">
                                <label>Jenis Standar</label>
                                <select class="form-control" required name="jenis_standar">
                                    <option value="">-- Select Standart --</option>
                                    <option value="KKNI">KKNI</option>
                                    <option value="Okupasi">Okupasi</option>
                                    <option value="Klaster">Klaster</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Klaster</label>
                                <select class="form-control" required name="id_klaster">
                                    <option value="">-- Select Cluster --</option>
                                    @foreach($data['cluster'] as $cluster)
                                    <option value="{{$cluster->id}}">{{$cluster->no_cluster}} - {{$cluster->judul_cluster}}</option>
                                    @endforeach
                                </select>
                            </div>
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                    </div>
                </div>
            </div>

            <!-- Edit Data -->
            <!-- route('admin.scheme.update', $id) -->
            <div class="modal fade" id="EditData" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="" id="form">
                        @csrf
                            <input type="hidden" id="id" value="">
                            <div class="form-group">
                                <label>Unit Code</label>
                                <input type="text" class="form-control" id="kode_unit" name="kode_unit" placeholder="Enter Unit Code" required autocomplete='off'>
                            </div>
                            <div class="form-group">
                                <label>Unit Title</label>
                                <input type="text" class="form-control" id="judul_unit" name="judul_unit" placeholder="Enter Unit Title" required autocomplete='off'>
                            </div>
                            <div class="form-group">
                                <label>Jenis Standar</label>
                                <select class="form-control" id="jenis_standar" required name="jenis_standar">
                                    <option value="">-- Select Standart --</option>
                                    <option value="KKNI">KKNI</option>
                                    <option value="Okupasi">Okupasi</option>
                                    <option value="Klaster">Klaster</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Klaster</label>
                                <select class="form-control" id="id_klaster" required name="id_klaster">
                                    <option value="">-- Select Cluster --</option>
                                    @foreach($data['cluster'] as $cluster)
                                    <option value="{{$cluster->id}}">{{$cluster->no_cluster}} - {{$cluster->judul_cluster}}</option>
                                    @endforeach
                                </select>
                            </div>
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </form>
                    </div>
                    </div>
                </div>
            </div>

<script src="{{URL::asset('public_html/__assets/js/lib/data-table/datatables.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/dataTables.bootstrap.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/dataTables.buttons.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.bootstrap.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/jszip.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/vfs_fonts.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.html5.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.print.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/lib/data-table/buttons.colVis.min.js')}}"></script>
<script src="{{URL::asset('public_html/__assets/js/init/datatables-init.js')}}"></script>
<script>
    @if(Session::has('success'))
        alert('Skema Klaster berhasil di tambah!')
    @endif
    @if(Session::has('delete'))
        alert('Skema Klaster berhasil di hapus!')
    @endif
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#bootstrap-data-table-export').DataTable();
    });

    function getEdit(e) {
        var id = $(e).data('id')
        var url = '{{route("admin.competency.index")}}/' + id + '/edit'

        $.ajax({
            method : 'get',
            url : url,
            dataType : 'json',
            success : function(data) {
                // console.log(data)
                $.each(data, function(i, item) {
                    $('#kode_unit').val(item.kode_unit)
                    $('#judul_unit').val(item.judul_unit)
                    $('#jenis_standar').val(item.jenis_standar)
                    $('#id_klaster').val(item.id_klaster)
                    $('#id').val(item.id)
                })
            }
        })
    }

    $('#form').on('submit', function(e) {
        e.preventDefault()
        var formData = $(this).serialize()
        var id = $('#id').val()
        var url = "{{route('admin.competency.index')}}/" + id

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $.ajax({
            method : 'PUT',
            url : url,
            data : formData,
            success : function(data) {
                alert(data.message)
                location.reload()
            }
        })
    })
</script>

@endsection