engine/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('user.login');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('registant', 'RegistantController');
    Route::get('registant/buktiKelengkapan/{index}/{id}', 'RegistantController@showKelengkapan')->name('registant.kelengkapan');
    Route::get('registant/buktiKompetensi/{index}/{id}', 'RegistantController@showKompetensi')->name('registant.kompetensi');
    Route::get('/registant/cluster/{id}', 'RegistantController@showCluster');
    Route::get('/registant/competency/{id}', 'RegistantController@showCompetency');
    Route::resource('assessor', 'AssessorController');
    Route::resource('scheme', 'SchemeController');
    Route::resource('competency', 'CompetencyController');
    Route::resource('participant', 'ParticipantController');
    Route::get('participant/apl/02/detail/{id_participant}/{id_cluster}', 'ParticipantController@detailApl02')->name('participant.apl02');
    Route::post('participant/apl/02/detail/{id_participant}/{id_asesor}', 'ParticipantController@detailApl02store')->name('participant.apl02.store');
    Route::post('participant/finish', 'ParticipantController@finish')->name('participant.finish');
    Route::resource('element', 'ElementController');
    Route::resource('question', 'QuestionController');
    Route::resource('school', 'SchoolController');
    Route::get('print/{id_participant}', 'PrintController@printAssignment')->name('print.assignment');
    Route::get('print/apl/02/{id_participant}/{id_cluster}/{id_asesor}', 'PrintController@printForm')->name('print.form');
});

Route::get('/login', 'AuthController@login')->name('user.login');
Route::get('/logout', 'AuthController@logout')->name('user.logout');
Route::get('/change/password', 'AuthController@editPassword')->name('user.change.password');
Route::put('/change/password', 'AuthController@updatePassword')->name('user.change.password.store');
Route::post('/loginPost', 'AuthController@loginPost')->name('user.login.post');
Route::get('/register', 'AuthController@register')->name('user.register');
Route::get('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02')->name('user.register02');
Route::post('/register/apl/02/{id_cluster}/{token}', 'AuthController@register02store')->name('user.register02.store');
Route::get('/register/confirm', 'AuthController@registerConfirm')->name('user.register02.confirm');

engine/app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    protected $fillable = [
        'id_registrasi',
        'id_asesor',
        'id_klaster',
        'kode_sekolah',
        'tempat_asesi',
        'tanggal_mulai_asesi',
        'tanggal_selesai_asesi',
        'ket_bukti_kelengkapan_persyaratan_1',
        'ket_bukti_kelengkapan_persyaratan_2',
        'ket_bukti_kelengkapan_persyaratan_3',
        'ket_bukti_kelengkapan_persyaratan_4',
        'ket_bukti_kompetensi_1',
        'ket_bukti_kompetensi_2',
        'ket_bukti_kompetensi_3',
        'ket_bukti_kompetensi_4',
        'status',
        'keterangan',
    ];

    public function asesor()
    {
        return $this->belongsTo('App\User', 'id_asesor');
    }

    public function registration()
    {
        return $this->belongsTo('App\Registration', 'id_registrasi');
    }

    public function cluster()
    {
        return $this->belongsTo('App\Cluster', 'id_klaster');
    }

    public function token()
    {
        return $this->hasOne('App\Token', 'id_participant');
    }

    public function answer()
    {
        return $this->hasMany('App\Answer', 'id_participant');
    }

    public function assessorAnswer()
    {
        return $this->hasMany('App\AssessorAnswer', 'id_participant');
    }

    public function school()
    {
        return $this->belongsTo('App\School', 'kode_sekolah', 'kode_sekolah');
    }
}

engine/app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\PrintController;

// model
use App\Participant;
use App\Registration;
use App\Token;
use App\Answer;
use App\Competence;
use App\AssessorAnswer;
use App\ValidAnswer;

class ParticipantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // validasi session login
        if(!Session::get('user')) {
            return redirect()->route('user.login');
        } else {
            // mengambil data participant dan mengambil data relasi registrasi dan relasi jawaban
            $data['participant'] = Participant::where('id_asesor', Session::get('userId'))->with('registration', 'answer')->get();

            return view('admin.participant.index', compact('data'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // mengambil data yang diinputkan user
        $id_registrasi = $request->id_registrasi;
        $id_asesor     = $request->id_asesor;
        $id_cluster    = $request->id_cluster;
        // $kode_sekolah  = $request->kode_sekolah;
        $tempat_asesi  = $request->tempat_asesi;
        $tanggal_mulai_asesi     = $request->tanggal_mulai_asesi;
        $tanggal_selesai_asesi   = $request->tanggal_selesai_asesi;
        $ket_bukti_kelengkapan_1 = $request->ket_bukti_kelengkapan_1;
        $ket_bukti_kelengkapan_2 = $request->ket_bukti_kelengkapan_2;
        $ket_bukti_kelengkapan_3 = $request->ket_bukti_kelengkapan_3;
        $ket_bukti_kompetensi_1  = $request->ket_bukti_kompetensi_1;
        $ket_bukti_kompetensi_2  = $request->ket_bukti_kompetensi_2;
        $ket_bukti_kompetensi_3  = $request->ket_bukti_kompetensi_3;
        $keterangan    = $request->keterangan;

        // tambah data ke database
        Participant::insert([
            'id_registrasi' => $id_registrasi,
            'id_asesor' => $id_asesor,
            'id_klaster' => $id_cluster,
            // 'kode_sekolah' => $kode_sekolah,
            'tempat_asesi' => $tempat_asesi,
            'tanggal_mulai_asesi' => $tanggal_mulai_asesi,
            'tanggal_selesai_asesi' => $tanggal_selesai_asesi,
            'ket_bukti_kelengkapan_persyaratan_1' => $ket_bukti_kelengkapan_1,
            'ket_bukti_kelengkapan_persyaratan_2' => $ket_bukti_kelengkapan_2,
            'ket_bukti_kelengkapan_persyaratan_3' => $ket_bukti_kelengkapan_3,
            'ket_bukti_kompetensi_1' => $ket_bukti_kompetensi_1,
            'ket_bukti_kompetensi_2' => $ket_bukti_kompetensi_2,
            'ket_bukti_kompetensi_3' => $ket_bukti_kompetensi_3,
            'status' => 'pending',
            'keterangan' => $keterangan
        ]);

        // mencari data registrasi
        $registration = Registration::where('id', $id_registrasi);
        // update data status registrasi
        $registration->update([
            'status' => 'in progress'
        ]);
        // mengambil nama pendaftar
        $name = $registration->select('nama_lengkap')->first();

        // mengambil data participant
        $data['participant']        = Participant::where('id_registrasi', $id_registrasi)->first();

        $data['hari_mulai']         = date('l', strtotime($data['participant']->tanggal_mulai_asesi));
        $data['tanggal_mulai']      = date('d', strtotime($data['participant']->tanggal_mulai_asesi));
        $data['bulan_mulai']        = date('F', strtotime($data['participant']->tanggal_mulai_asesi));
        $data['tahun_mulai']        = date('Y', strtotime($data['participant']->tanggal_mulai_asesi));
        
        $data['hari_selesai']       = date('l', strtotime($data['participant']->tanggal_selesai_asesi));
        $data['tanggal_selesai']    = date('d', strtotime($data['participant']->tanggal_selesai_asesi));
        $data['bulan_selesai']      = date('F', strtotime($data['participant']->tanggal_selesai_asesi));
        $data['tahun_selesai']      = date('Y', strtotime($data['participant']->tanggal_selesai_asesi));

        $data['bulan_mulai']        = app('App\Http\Controllers\PrintController')->month($data['bulan_mulai']);
        $data['bulan_selesai']      = app('App\Http\Controllers\PrintController')->month($data['bulan_selesai']);
        $data['hari_mulai']         = app('App\Http\Controllers\PrintController')->day($data['hari_mulai']);
        $data['hari_selesai']       = app('App\Http\Controllers\PrintController')->day($data['hari_selesai']);

        $data['tempat_asesi']       = $data['participant']->tempat_asesi;

        // mengambil input email
        $email = $request->email;
        // mengoper data ke view email
        $data = [
            'name' => $name,
            'hari_mulai' => $data['hari_mulai'],
            'tanggal_mulai' => $data['tanggal_mulai'],
            'bulan_mulai' => $data['bulan_mulai'],
            'tahun_mulai' => $data['tahun_mulai'],
            'hari_selesai' => $data['hari_selesai'],
            'tanggal_selesai' => $data['tanggal_selesai'],
            'bulan_selesai' => $data['bulan_selesai'],
            'tahun_selesai' => $data['tahun_selesai'],
            'tempat_asesi' => $data['tempat_asesi'],
            'link' => route('user.register02', ['token' => $this->token($data['participant']->id), 'id_cluster' => $id_cluster])
        ];
        // kirim email ke pendaftar
        $this->sendEmail($data, $email);

        return redirect()->route('admin.registant.index')->with('success', true);
    }

    // fungsi kirim email ke pendaftar
    public function sendEmail($data, $email)
    {
        \Mail::send('email.email', $data, function($mail) use($email) {
            $mail->to($email, 'no-reply')
                    ->subject('Formulir APL-02');
            $mail->from('teampengembang26@gmail.com', 'LSP SMK Negeri 26');
        });
    }

    // fungsi membuat random token
    public function token($id_participant)
    {
        $token = \Str::random(30);
        Token::insert([
            'id_participant' => $id_participant,
            'token' => $token,
        ]);

        return $token;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // mengambil data participant berdasarkan id
        // dan mengambil data relasi registrasi, asesor, klaster, dan jawaban asesor
        $data = Participant::where('id', $id)
                            ->with('registration', 'asesor', 'cluster', 'assessorAnswer', 'school')
                            ->first();
        
        return response()->json([
            'data' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function detailApl02($id_participant, $id_cluster)
    {
        // validasi session login
        if(!Session::get('user')) {
            return redirect()->route('user.login');
        } else {
            // mengambil data untuk detail form APL 02
            $data['competence']     = Competence::where('id_klaster', $id_cluster)->with('element')->get();
            $data['answer']         = Answer::where('id_participant', $id_participant)->get();
            $data['asesor_answer']  = AssessorAnswer::where('id_participant', $id_participant)->get();
            $data['valid_answer']   = ValidAnswer::orderBy('id', 'ASC')->get();
            $data['status']         = Participant::select('status')->where('id', $id_participant)->first();
            $data['id_participant'] = $id_participant;
            $data['id_cluster']     = $id_cluster;
            $data['id_asesor']      = Session::get('userId');

            return view('admin.participant.apl02', compact('data'));
        }
    }

    public function detailApl02store(Request $request, $id_participant, $id_asesor)
    {
        // tambah data jawaban asesor ke database
        foreach($request->penilaian as $penilaian) {
            $explode = explode("-", $penilaian);
            AssessorAnswer::insert([
                'id_participant' => $id_participant,
                'id_asesor' => $id_asesor,
                'id_pertanyaan' => $explode[1],
                'id_jawaban' => $explode[0]
            ]);
        }

        return redirect()->route('admin.participant.index')->with('success', 'true');
    }

    public function finish(Request $request)
    {
        // mengambil data participant berdasarkan id participant
        $singleRecord  = Participant::where('id', $request->id_participant);
        $participant   = $singleRecord->first();
        
        // update data status participant
        $singleRecord->update([
            'status' => 'complete'
        ]);

        // update data status registrasi
        Registration::where('id', $participant->id_registrasi)->update([
            'status' => 'complete'
        ]);

        return redirect()->route('admin.participant.index')->with('success', 'true');
    }
}

engine/resources/views/admin/participant/apl02.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{asset('public_html/__images/logo-login.png')}}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Register APL 02</title>
  </head>
  <body>  
    <div class="container mt-3">
        <h2>FR-APL-02. ASESMEN MANDIRI</h2>
        <p> <b>
            Peserta diminta untuk:  
            <br>
            1.	Mempelajari Kriteria Unjuk Kerja  (KUK), Batasan Variabel, Panduan Penilaian, dan Aspek Kritis seluruh Unit Kompetensi yang diminta untuk di Ases.
            <br>
            2.	Melaksanakan Penilaian Mandiri secara obyektif atas sejumlah pertanyaan yang diajukan, bilamana Anda menilai diri sudah kompeten atas pertanyaan tersebut, tuliskan tanda  pada kolom (K), dan bilamana Anda menilai diri belum kompeten tuliskan tanda  pada kolom (BK).
            <br>
            3.	Mengisi bukti-bukti kompetensi yang relevan atas sejumlah pertanyaan yang dinyatakan Kompeten (bila ada). 
            <br>
            4.	Menandatangani form Asesmen Mandiri.
            </b>
        </p>
        <form action="{{route('admin.participant.apl02.store', ['id_participant' => $data['id_participant'], 'id_asesor' => $data['id_asesor']])}}" method="POST">
        @csrf
        @foreach($data['competence'] as $competence)
        @if(!$competence->element->isEmpty())
        <table class="table table-bordered text-center mt-5 table-primary">
            <thead>
                <tr>
                    <th rowspan="2" style="line-height: 100px;">Uji Kompetensi No. {{$loop->iteration}}</th>
                    <th>Kode Unit</th>
                    <th>:</th>
                    <th>{{$competence->kode_unit}}</th>
                </tr>
                <tr>
                    <th>Judul Unit</th>
                    <th>:</th>
                    <th>{{$competence->judul_unit}}</th>
                </tr>
            </thead>
        </table>
        @endif
        @foreach($competence->element as $element)
        <table class="table table-bordered text-left mt-2 table-dark">
            <thead>
                <tr>
                    <th>Elemen Kompetensi</th>
                    <th style="text-align: center;">:</th>
                    <th>{{$loop->iteration}}. {{$element->elemen_kompetensi}}</th>
                </tr>
            </thead>
        </table>

        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th rowspan="2" style="line-height: 100px;">No. KUK</th>
                    <th rowspan="2" style="line-height: 100px;">Daftar Pertanyaan (Asesmen Mandiri/Self  Assessment)</th>
                    <th colspan="2">Penilaian</th>
                    <th colspan="4">Asesor</th>
                </tr>
                <tr>
                    <th>K</th>
                    <th>BK</th>
                    @foreach($data['valid_answer'] as $validAnswer)
                    <th>{{$validAnswer->jawaban}}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($element->question as $question)
                <tr>
                    <th>{{$question->no_kuk}}</th>
                    <td width="65%">{{$question->daftar_pertanyaan}}</td>
                    @foreach($data['answer'] as $answer)
                        @if($answer->id_pertanyaan == $question->id)
                            @if($answer->jawaban == 'K')
                                <td><span>&#x2713;</span></td>
                                <td></td>
                            @else
                                <td></td>
                                <td><span>&#x2713;</span></td>
                            @endif
                        @endif
                    @endforeach
                    @if($data['status']->status === 'in progress' && $data['asesor_answer']->isEmpty())
                        @foreach($data['valid_answer'] as $validAnswer)
                            <td><input type="checkbox" name="penilaian[]" value="{{$validAnswer->id}}-{{$question->id}}"></td>
                        @endforeach
                    @else        
                        @foreach($data['valid_answer'] as $validAnswer)
                            <?php $answerStat = false ?>
                            @foreach($data['asesor_answer'] as $key => $asesorAnswer)
                                @if($asesorAnswer->id_pertanyaan === $question->id && $asesorAnswer->id_jawaban === $validAnswer->id)
                                    <?php $answerStat = true ?>
                                    <td><span>&#x2713;</span></td>
                                @endif
                            @endforeach
                            @if($answerStat == false)
                                <td></td>
                            @endif
                        @endforeach
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>
        @endforeach
        @endforeach
        <div class="row form-group">
            <div class="col col-md-9">
                <div class="form-check-inline form-check">
                    <label for="check" class="form-check-label">
                        <input type="checkbox" id="check" name="check" value="on" class="form-check-input">Check All Form
                    </label>
                </div>
            </div>
        </div>
        @if($data['status']->status === 'in progress' && $data['asesor_answer']->isEmpty())
        <div class="text-right">
            <button class="btn btn-primary">Submit</button>
        </div>
        @else
        <div class="text-right">
            <a href="{{route('admin.print.form', ['id_participant' => $data['id_participant'], 'id_cluster' => $data['id_cluster'], 'id_asesor' => $data['id_asesor']])}}" target="_blank">
                <button type="button" class="btn btn-success">Download Form</button>
            </a>
        </div>
        @endif
        </form>
        <br><br>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpatd.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
        $("#check").click(function(){
            $('input:checkbox').not(this).prop('checked', this.checked);
        });
    </script>
  </body>
</html>

engine/resources/views/admin/participant/printApl02.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Form APL 02 {{$data['participant']->registration->nama_lengkap}}</title>
  </head>
  <body>
    

    
    <div class="container">
        <table class="table table-bordered text-left">
            <tr>
                <th rowspan="3">Skema Sertifikasi / Klaster Asesmen*</th>
            </tr>
            <tr>
                <th>Judul</th>
                <th>:</th>
                <th style="text-transform: uppercase;">{{$data['participant']->registration->cluster->judul_cluster}}</th>
            </tr>
            <tr>
                <th>Nomor</th>
                <th>:</th>
                <th>KKNI {{$data['participant']->registration->cluster->department->level_jurusan}} TKJ / KLASTER {{$data['participant']->registration->cluster->no_cluster}}</th>
            </tr>
            <tr>
                <th colspan="2">TUK</th>
                <th>:</th>
                <th>Sewaktu / Tempat Kerja / Mandiri*</th>
            </tr>
            <tr>
                <th colspan="2">Nama Asesor</th>
                <th>:</th>
                <th>{{$data['asesor']->nama_lengkap}}</th>
            </tr>
            <tr>
                <th colspan="2">Nama Peserta</th>
                <th>:</th>
                <th>{{$data['participant']->registration->nama_lengkap}}</th>
            </tr>
            <tr>
                <th colspan="2">Tanggal</th>
                <th>:</th>
                <td></td>
            </tr>
        </table>
        <span><p><i>* Coret yang tidak perlu</i></p></span>

        <p> <b>
        Peserta diminta untuk:  
            <br>
            1.	Mempelajari Kriteria Unjuk Kerja  (KUK), Batasan Variabel, Panduan Penilaian, dan Aspek Kritis seluruh Unit Kompetensi yang diminta untuk di Ases.
            <br>
            2.	Melaksanakan Penilaian Mandiri secara obyektif atas sejumlah pertanyaan yang diajukan, bilamana Anda menilai diri sudah kompeten atas pertanyaan tersebut, tuliskan tanda  pada kolom (K), dan bilamana Anda menilai diri belum kompeten tuliskan tanda  pada kolom (BK).
            <br>
            3.	Mengisi bukti-bukti kompetensi yang relevan atas sejumlah pertanyaan yang dinyatakan Kompeten (bila ada). 
            <br>
            4.	Menandatangani form Asesmen Mandiri.
            </b>
        </p>
        <br><br>
        <form action="" method="POST">
        @foreach($data['competence'] as $competence)
        @if(!$competence->element->isEmpty())
        <table class="table table-bordered mt-4 text-center">
            <thead>
                <tr>
                    <th rowspan="2" style="line-height: 100px;">Uji Kompetensi No. {{$loop->iteration}}</th>
                    <th>Kode Unit</th>
                    <th>:</th>
                    <th>{{$competence->kode_unit}}</th>
                </tr>
                <tr>
                    <th>Judul Unit</th>
                    <th>:</th>
                    <th>{{$competence->judul_unit}}</th>
                </tr>
            </thead>
        </table>
        @endif
        @foreach($competence->element as $element)
        <table class="table table-bordered mt-2 text-center">
            <thead>
                <tr>
                    <th>Elemen Kompetensi</th>
                    <th>:</th>
                    <th colspan="6">{{$loop->iteration}}. {{$element->elemen_kompetensi}}</th>
                </tr>
                <tr class="table-primary">
                    <th rowspan="2" style="line-height: 100px;">No. KUK</th>
                    <th rowspan="2" style="line-height: 100px;">Daftar Pertanyaan (Asesmen Mandiri/Self  Assessment)</th>
                    <th colspan="2">Penilaian</th>
                    <th colspan="4">Asesor</th>
                </tr>
                <tr class="table-primary">
                    <th>K</th>
                    <th>BK</th>
                    @foreach($data['valid_answer'] as $validAnswer)
                    <th>{{$validAnswer->jawaban}}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($element->question as $question)
                <tr>
                    <th>{{$question->no_kuk}}</th>
                    <td width="80%">{{$question->daftar_pertanyaan}}</td>
                    @foreach($data['answer'] as $answer)
                        @if($answer->id_pertanyaan == $question->id)
                            @if($answer->jawaban == 'K')
                                <td><span class="check">&#x2713;</span></td>
                                <td></td>
                            @else
                                <td></td>
                                <td><span class="check">&#x2713;</span></td>
                            @endif
                        @endif
                    @endforeach
                    @foreach($data['valid_answer'] as $validAnswer)
                        <?php $answerStat = false ?>
                        @foreach($data['asesor_answer'] as $asesorAnswer)
                            @if($asesorAnswer->id_pertanyaan === $question->id && $asesorAnswer->id_jawaban === $validAnswer->id)
                                <?php $answerStat = true ?>
                                <td><span class="check">&#x2713;</span></td>
                            @endif
                        @endforeach
                        @if($answerStat == false)
                            <td></td>
                        @endif
                    @endforeach
                </tr>
                @endforeach
            </tbody>
        </table>
        @endforeach
        @endforeach
        <table class="table table-bordered text-left">
            <tr>
                <th>Rekomendasi Asesor</th>
                <th colspan="2">Peserta   :</th>
            </tr>
            <tr>
                <td rowspan="3">
                    <p>1. Asesmen dapat / tidak dapat *) dilanjutkan</p>
                    <p>2. Proses Asesmen dapat dilanjutkan melalui</p>
                    &#20; Asesmen Portfolio
                    <br>
                    &#20; Uji Kompetensi
                </td>
            </tr>
            <tr>
                <td width="10%">Nama</td>
                <td width="30%">{{$data['participant']->registration->nama_lengkap}}</td>
            </tr>
            <tr>
                <td>Tanda Tangan / Tanggal</td>
                <td></td>
            </tr>
            <tr>
                <th>Catatan</th>
                <th colspan="2">Asesor :</th>
            </tr>
            <tr>
                <td rowspan="4"></td>
            </tr>
            <tr>
                <td>Nama</td>
                <td>{{$data['asesor']->nama_lengkap}}</td>
            </tr>
            <tr>
                <td>No Reg</td>
                <td>{{$data['asesor']->no_reg}}</td>
            </tr>
            <tr>
                <td>Tanda Tangan / Tanggal</td>
                <td></td>
            </tr>
        </table>
        </form>
        <br><br>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpatd.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            window.print()
        })
    </script>
  </body>
</html>